description: >
  Docker image with only the minimal tools needed to run a build. Based on Docker Alpine

parameters:
  tag:
    type: string
    default: latest
    description: >
      The tag of the docker image. See the following for the full list.
      https://hub.docker.com/r/cibuilds/base/tags

docker:
  - image: cibuilds/base:<< parameters.tag >>
